---

cloudinit:
  image: https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-generic-amd64.qcow2
  templates:
    config: debian-config.j2
    network: debian-network.j2

vm:
  name: debian12-server
  hostname: debian.example.org
  desc: VM with Debian 12 server (cloud-init)

  os: debian11

  hardware:
    cpu: 2
    memory: 4096

  disk:
    size: 50G

...
