---
# When no network is found (second boot) press <Shift> + <F10> to open a
# command prompt. Then enter `OOBE\BYPASSNRO` and press <Enter>. The computer
# restart automatically and the out-of-box experience (OOBE) will start again.
# Now you can select 'I don't have Internet' and 'Continue with limited setup'.

unattend:
  template: unattend_win11.j2
  windows_version: Windows 11 Pro
  # Use generic product keys from
  # https://learn.microsoft.com/en-us/windows-server/get-started/kms-client-activation-keys
  product_key: W269N-WFGWX-YVC9B-4J6C9-T83GX
  input: 0409:00000407
  language: en-US
  locale: en-DE
  timezone: W. Europe Standard Time
  # wait after setup script on first boot
  debug: true

vm:
  name: windows11
  hostname: w11.example.org
  desc: VM with Windows 11

  # get more infos: `osinfo-query os`
  os: win11

  hardware:
    cpu: 4
    memory: 8192

  disk:
    # disk size must be larger than 60GB
    size: 70G

  cdrom: Win11_22H2_English_x64v2.iso
...
